
[phases.setup]
nixPkgs = ["...", "ffmpeg"]

[phases.install]
cmds = [
    "python -m venv .venv",
    ".venv/bin/pip install --upgrade pip",
    ".venv/bin/pip install pyTelegramBotAPI gTTS groq moviepy"
]

[start]
cmd = ".venv/bin/python main.py"
